-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	created_at timestamp(6) NULL,
	is_deleted bool NULL,
	updated_at timestamp(6) NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone varchar(255) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
	CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id),
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id)
);


INSERT INTO public.roles
(id, "name")
VALUES(1, 'USER');
INSERT INTO public.roles
(id, "name")
VALUES(2, 'ADMIN');


INSERT INTO public.user_roles
(user_id, role_id)
VALUES(1, 1);
INSERT INTO public.user_roles
(user_id, role_id)
VALUES(2, 1);
INSERT INTO public.user_roles
(user_id, role_id)
VALUES(3, 2);


INSERT INTO public.users
(id, created_at, is_deleted, updated_at, email, "name", "password", phone)
VALUES(2, '2024-05-25 22:25:52.959', false, NULL, 'joyo@gmail.com', 'joyo', '$2a$10$.x.CtHJ9FmhD1yFjWmN8OuwkVtEnB4z1czTyL.BaKaRZiLz47qOC2', '082123123123');
INSERT INTO public.users
(id, created_at, is_deleted, updated_at, email, "name", "password", phone)
VALUES(3, '2024-05-25 22:26:47.392', false, NULL, 'joyi@gmail.com', 'joyi', '$2a$10$J9cl1bhjFdEwLjOMr7C8H.kgYJQRCTRjOfP2TkDj8dBrVFYuMxi.O', '083123123123');
INSERT INTO public.users
(id, created_at, is_deleted, updated_at, email, "name", "password", phone)
VALUES(1, '2024-05-25 22:05:06.129', false, '2024-05-26 13:02:00.126', 'jayi@gmail.com', 'jayi', '$2a$10$cgA.vhUjTR8kaIXFDsEaL.SLH5vdamckxh3OgCHMKOQyY632MKaVC', '081123123123');
